#!/usr/bin/python

import os
import sys
import subprocess
import shlex

sys.path.insert(0, os.path.join(os.environ['CHARM_DIR'], 'lib'))

from charmhelpers.core import (
    hookenv,
    host,
)

hooks = hookenv.Hooks()
log = hookenv.log


@hooks.hook('start')
def stop():
    if not os.path.exists('.logstash'):
        print "Unable to locate logstash host - exiting"
        return 0

    with open('.logstash') as f:
        logstash_host = f.read()

    cmd = "docker run -d -e ROUTE_URIS=logstash://{}:5000 -v /var/run/docker.sock:/tmp/docker.sock logspout".format(logstash_host)
    subprocess.check_call(shlex.split(cmd))


if __name__ == "__main__":
    # execute a hook based on the name the program is called by
    hooks.execute(sys.argv)
